name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: Update npm
        run: npm install npm@latest --legacy-peer-deps
      - name: Update dependencies
        run: npm update --legacy-peer-deps
      - name: Create package-lock.json
        run: npm install --legacy-peer-deps
      - name: Install dependencies
        run: npm ci
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release