name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Get Version from package.json
        id: version
        run: echo "::set-output name=version::$(node -e "console.log(require('./package.json').version)")"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ''
          body: |
            Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          tag_name: "v${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
